name: 'GitHub Actions test echo'
 
on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Run a one-line script
         run: echo Hello, github action!
