name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install NPM dependencies'
        run: echo hello github

