name: 'GitHub Actions test echo'
 
on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Run a one-line script
         run: echo Hello, github action!
